### PR TITLE
[#57][WIP] Add requirement for Pimcore 10

### PR DESCRIPTION
**Pull request by jorisros**

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
@jorisros I guess that is pretty much it right?

**Comment by jorisros** [comment]
Unfortunately not yet, getting the error below (something with the service i guess). Have to dive into this tonight

`Timestamp: Tue May 25 2021 12:00:39 GMT+0200 (Central European Summer Time)
Status: 500 | Internal Server Error
URL: /admin/workflow/list?_dc=1621936838995
Method: GET
Message: The controller for URI "/admin/workflow/list" is not callable: Controller "WorkflowGuiBundle:Workflow:list" does neither exist as service nor as class.
Trace: 
in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php:88
#0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/TraceableControllerResolver.php(38): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request))
#1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(140): Symfony\Component\HttpKernel\Controller\TraceableControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request))
#2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(79): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#3 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(195): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#4 /var/www/html/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#5 {main}`

**Comment by dpfaffenbauer** [comment]
@jorisros I fixed and further prepared it, can you give it a try?

**Comment by jorisros** [comment]
It seems that by accident there where added a lot of configuration/other files added, that shouldnt belong in a plugin:
- .env
- bin/console
- config/config.yaml
- config/packages/security.yaml 
- etc ...

Belong those in the plugins?

**Comment by dpfaffenbauer** [comment]
I've added that on purpose. That is how I develop and maintain bundles: I just need to clone the repo, do a composer install and can directly work on the bundle.

**Review by dpfaffenbauer — APPROVED** [review]

**Pull request merged**
